MCU = RP2040
SPLIT_KEYBOARD = yes
BOOTLOADER = rp2040
SERIAL_DRIVER = vendor

MOUSEKEY_ENABLE = yes
CONSOLE_ENABLE = no
#COMMAND_ENABLE = yes
BOOTMAGIC_ENABLE = yes

OLED_ENABLE = no
OLED_DRIVER = ssd1306
OLED_TRANSPORT = i2c

WPM_ENABLE = yes
EXTRAKEY_ENABLE = yes
NKRO_ENABLE = yes

ENCODER_ENABLE = no
ENCODER_MAP_ENABLE = no

RGB_MATRIX_ENABLE = yes
VIALRGB_ENABLE = yes
WS2812_DRIVER = vendor
SLEEP_LED_ENABLE = no

OPT_DEFS += -DHAL_USE_I2C=TRUE

QMK_SETTINGS_ENABLE = no   # 🔧 Prevent build errors
TAP_DANCE_ENABLE = no
KEY_OVERRIDE_ENABLE = no